### ISSUE TITLE
[Feat] : Spot domain 구현

### ISSUE THREAD

**Issue by sanggae4133** [AR-TTUBEOG/Back-Spring#17]
## ✏️ Description
Spot domain 관련 API를 구현합니다.

## To-Do List
- [x] 산책 스팟 등록
- [x] 산책 스팟 세부 사항 조회
- [x] 산책 스팟 수정
- [x] 산책 스팟 삭제
- [ ] 산책 스팟 방명록 작성
- [ ] 산책 스팟 좋아요 누르기

## ETC
프로젝트 세팅한다고 domain 구현 늦어서 죄송함미다.. 이번 주 내로 무적권 다 끝내기..!
