### ISSUE TITLE
[Feat] : 장소 전체 조회 및 검색 구현

### ISSUE THREAD

**Issue by Jeongmin39** [AR-TTUBEOG/Back-Spring#34]
## ✏️ Description
Place 도메인을 만들고 Store와 Spot을 대상으로 하는 전체 조회와 검색 기능을 구현합니다. 

## To-Do List
- [x] Place 도메인 작성
- [x] 장소 전체 조회 구현
- [x] 장소 검색 구현

## ETC
