### ISSUE TITLE
[Feat] : 회원탈퇴 기능 구체화에 따른 로직 수정

### ISSUE THREAD

**Issue by arinming** [AR-TTUBEOG/Back-Spring#60]
## ✏️ Description
회원탈퇴 기능이 구체화되어 이에 따라 로직을 수정합니다.
탈퇴 이후 72시간동안 INACTIVE 상태임은 동일, INACTIVE된 회원은 ACTIVE로 변경될 수 없습니다.

- 산책로만 등록된 경우 바로 회원탈퇴 가능.
- 매장이 등록되어 있는 회원인 경우, 고객에게 쿠폰이 발급되었다면 탈퇴 불가능.
-> 고객이 쿠폰을 모두 사용했거나, 쿠폰 발급으로부터 한 달이 지난 경우 탈퇴 가능.

## To-Do List
- [ ] 해당 회원의 매장 등록 여부 조회
- [ ] 매장 등록 안된 경우 회원탈퇴
- [ ] 매장 등록 된 경우 쿠폰 발급 여부 조회
- [ ] 발급한 쿠폰이 없는 경우 회원탈퇴
- [ ] 쿠폰 발급일로부터 한달이 지나지 않은 경우 회원탈퇴 불가
- [ ] 회원 탈퇴시 연관된 테이블 삭제
