### ISSUE TITLE
[Refactor] : ResponseEntity 분리

### ISSUE THREAD

**Issue by choeun7** [AR-TTUBEOG/Back-Spring#87]
## ✏️ Description
ResponseEntity가 의미없이 반복되는 부분이 많아서 따로 분리할 예정입니다.

## To-Do List
- [ ] ResponseEntity 분리 파일 생성
- [ ] 예시 api 하나 적용
- [ ] 노션 설명 작성
