### ISSUE TITLE
[Refactor] : Place 조회 필터 적용 시 발생하는 문제 해결

### ISSUE THREAD

**Issue by Jeongmin39** [AR-TTUBEOG/Back-Spring#99]
## ✏️ Description
현재 전체 장소 조회 시 필터를 적용하면 발생하는 문제를 해결합니다.

## To-Do List
- [ ] 최신순 조회 리팩토링
- [ ] 거리순 조회 리팩토링
- [ ] 추천순 조회 리팩토링

## ETC
필터(최신순, 거리순, 추천순) 적용 시 Store, Spot끼리 따로 정렬되어 나오는 문제를 해결할 예정입니다 !
